apiVersion: v1
kind: Service
metadata:
  labels:
    challenge.app: network-stats
  name: network-stats
spec:
  ports:
    - name: "web"
      port: 80
      targetPort: web # line 47
  selector:
    challenge.app: network-stats
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    challenge.app: network-stats
  name: network-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      challenge.app: network-stats
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        challenge.app: network-stats
        team: DevOps
    spec:
      containers:
        - name: network-stats
          envFrom:
            - configMapRef:
                name: network-stats-config
          image: dxas90/network-stats # https://gitlab.com/dxas90/network-stats
          ports:
            - name: web
              containerPort: 5000 # line 11
              protocol: TCP
          resources:
            limits:
              cpu: 10m
              memory: 56Mi
            requests:
              cpu: 10m
              memory: 56Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-stats-config # line 43
data:
  APP_ENV: prod
  APP_THREADS: "1"
  INTERVAL: "30"
  LOGLEVEL: info
  MAILER_URL: "smtp://mail-server:1025"
  MONGODB_URL: "mongodb://mongodb:27017"
  REDIS_DSN: "redis://redis:6379?timeout=0.5"
---
